### ISSUE TITLE
Trackpad Tap to click is weird

### ISSUE THREAD

**Issue by Rex-tc** [Canary-Prism/SadnessClicker#1]
if using tap to click, you can spam click on the "Click" button, and, as long as you don't move the cursor, it will still register even if the button moves out of the way

but randomlyish while clicking the cursor will teleport to a fixed location on screen

**Comment by Canary-Prism** [comment]
thisss..... is a funny glitch lmao
i don't think it matters much, in the sense that this program was *meant* to be infuriating
given the inconsistency and the cursor teleporting i think this is good enough lol
i'll keep it
and it's more of a macOS bug anyway
